# Timeout for commands (ms)
command_timeout = 1000

# Newline between prompts
add_newline = false

format = "$directory$git_branch$git_metrics$character"
right_format = "$git_status$git_commit$git_state"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " ğŸ”’"
read_only_style = "red"
truncation_length = 0
truncate_to_repo = true
home_symbol = "~"

[git_branch]
format = "[ó°˜¬](bold white) [$branch(:$remote_branch)]($style) "
symbol = ""
style = "bold blue"
# truncation_length = 25

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bold yellow"
conflicted = "âš”ï¸"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?"
stashed = "ğŸ“¦"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style) )'
added_style = "bold green"
deleted_style = "bold red"

[git_commit]
format = "[ $hash$tag]($style) "
style = "bold green"
only_detached = true
tag_disabled = false
tag_symbol = "  "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bold yellow"
rebase = " REBASING"
merge = "ó°˜­ MERGING"
revert = " REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = " BISECTING"
am = " AM"
am_or_rebase = " AM/REBASE"

[character]
format = "$symbol "
success_symbol = "[â¯](bold white)"
error_symbol = "[â¯](bold red)"

[time]
disabled = false
format = "[$time]($style)"
style = "bold dimmed white"
time_format = "%H:%M"
